# Generated by Django 2.0.7 on 2018-07-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='year',
            field=models.PositiveSmallIntegerField(default=2018, max_length=4),
        ),
    ]
